ansible_pull_repo_url: "https://github.com/csedm/cloud-infra-config.git"
ansible_pull_branch: "main"
ansible_pull_playbook: "ansible/local.yml"
ansible_pull_dest: "/opt/ansible"
ansible_pull_inventory: "{{ ansible_pull_dest }}/ansible/inventory"
packer_image_roles: [
  "common" 
]

ansible_ssh_common_args: "-o ForwardAgent=yes -o ProxyJump=ansible@{{ aws_bastion_host }}"