# configuration for default hostname of a packer image
ansible_ssh_common_args: ""

# custom_default_user: "{{ lookup('env', 'CUSTOM_DEFAULT_USER') }}"
# Extract user items where role_presence contains bootstrap
# Filter out the custom_default_user, which is handled by the packer config
# This is a special carve-out from the common config in group_vars/all.yml
# custom_default_user must be set by -e on the ansible provisioner in the packer template.

dynamic_required_users_list: >-
  [{% for u in common_user_information_base
      if u.role_presence | intersect(effective_roles) | length > 0
      and u.name != custom_default_user %}
    {{ u | to_json }}{% if not loop.last %},{% endif %}
  {% endfor %}]

dynamic_required_ssh_authorized_keys_list: >-
  [{% for u in common_user_information_base
      if u.role_presence | intersect(effective_roles) | length > 0
      and u.name != custom_default_user
      and u.sshpubkeys is defined and u.sshpubkeys | length > 0 %}
    {
      "name": "{{ u.name }}",
      "sshpubkeys": {{ u.sshpubkeys | to_json }},
      "sshpubkeys_exclusive": {{ u.sshpubkeys_exclusive | default(false) | to_json }}
    }{% if not loop.last %},{% endif %}
  {% endfor %}]
