---
- name: Ensure package states are correctly present or absent
  ansible.builtin.package:
    name: "{{ package.name }}"
    state: "{{ package.state }}"
  loop: "{{ dynamic_required_packages_list }}"
  loop_control:
    loop_var: package
  tags:
    - package

- name: Create required groups
  ansible.builtin.group:
    name: "{{ group.name }}"
    gid: "{{ group.gid | default(omit) }}"
    state: "{{ group.state }}"
  loop: "{{ dynamic_required_groups_list }}"
  loop_control:
    loop_var: group

- name: Create required users
  ansible.builtin.user:
    name: "{{ user.name }}"
    state: "{{ user.state }}"
    uid: "{{ user.uid | default(omit) }}"
    group: "{{ user.primary_group }}"
    groups: "{{ user.groups }}"
    # while we want the password locked, doing so prevents ssh login on certain platforms.
    # so we set it to * to prevent password login, but allow ssh key login.
    password_lock: false
    password: "*"
  loop: "{{ dynamic_required_users_list }}"
  loop_control:
    loop_var: user

- name: Set required ssh authorized_keys
  ansible.posix.authorized_key:
    user: "{{ user_key.name }}"
    key: "{{ user_key.sshpubkeys | map(attribute='key') | join('\n') }}"
    state: present
    exclusive: "{{ user_key.sshpubkeys_exclusive }}"
  loop: "{{ dynamic_required_ssh_authorized_keys_list }}"
  loop_control:
    loop_var: user_key

- name: Ensure required doas user configuration
  ansible.builtin.lineinfile:
    path: /etc/doas.conf
    regexp: "^permit nopass {{ user.name }}"
    line: "permit nopass {{ user.name }}"
    mode: '0640'
    state: "{{ user.state }}"
    create: true
    backup: true
    validate: 'doas -C %s'
  loop: "{{ dynamic_required_sudo_users }}"
  loop_control:
    loop_var: user
  when: ansible_become_method == 'community.general.doas'

- name: Ensure required doas group configuration
  ansible.builtin.lineinfile:
    path: /etc/doas.conf
    regexp: "^permit nopass :{{ group.name }}"
    line: "permit nopass :{{ group.name }}"
    mode: '0640'
    state: "{{ group.state }}"
    create: true
    backup: true
    validate: 'doas -C %s'
  loop: "{{ dynamic_required_sudo_groups }}"
  loop_control:
    loop_var: group
  when: ansible_become_method == 'community.general.doas'

- name: Ensure required sudoer user configuration
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/00-ansible-common
    regexp: "^{{ user.name }}"
    line: "{{ user.name }} ALL=(ALL) NOPASSWD:ALL"
    mode: '0440'
    state: "{{ user.state }}"
    create: true
    backup: true
    validate: 'visudo -cf %s'
  loop: "{{ dynamic_required_sudo_users }}"
  loop_control:
    loop_var: user
  when: ansible_become_method == 'ansible.builtin.sudo'

- name: Ensure required sudoer group configuration
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/00-ansible-common
    regexp: "^%{{ group.name }}"
    line: "%{{ group.name }} ALL=(ALL) NOPASSWD:ALL"
    mode: '0440'
    state: "{{ group.state }}"
    create: true
    backup: true
    validate: 'visudo -cf %s'
  loop: "{{ dynamic_required_sudo_groups }}"
  loop_control:
    loop_var: group
  when: ansible_become_method == 'ansible.builtin.sudo'

- name: Include ssh configuration
  ansible.builtin.include_tasks: ssh.yml

- name: Include security configuration
  ansible.builtin.include_tasks: security.yml
