---
- name: Install standard packages by OS Family
  ansible.builtin.package:
   name: "{{ item }}"
   state: present
  with_items: "{{ common_packages[ansible_os_family] }}"
  when: (common_packages[ansible_os_family] is defined) and (common_packages[ansible_os_family] | length > 0)
  tags:
  - package

- name: Remove undesirable packages by OS family
  ansible.builtin.package:
   name: "{{ item }}"
   state: absent
  with_items: "{{ common_uninstall_packages[ansible_os_family] }}"
  when: (common_uninstall_packages[ansible_os_family] is defined) and (common_uninstall_packages[ansible_os_family] | length > 0)
  tags:
  - package
