---
- name: Ensure /etc/ssh/sshd_config.d/ exists
  ansible.builtin.file:
    path: /etc/ssh/sshd_config.d/
    state: directory
    owner: root
    group: 0
    mode: '0750'
  tags:
    - ssh
    - config

- name: Ensure sshd_config.d/ include directive exists
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    insertbefore: '^#Port 22'
    firstmatch: true
    line: 'Include /etc/ssh/sshd_config.d/*.conf'
    validate: '/usr/sbin/sshd -t -f %s'
    backup: true
  notify: "Common : restart sshd"
  tags:
  - ssh
  - config

- name: Enable ssh agent forwarding
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^AllowAgentForwarding no'
    line: 'AllowAgentForwarding yes'
    state: present
  notify: "Common : restart sshd"
