- name: Create common groups
  ansible.builtin.group:
    name: "{{ group.name }}"
    gid: "{{ group.gid | default(omit) }}"
    state: "{{ group.state }}"
  loop: "{{ common_groups }}"
  loop_control:
    loop_var: group

- name: Create common users
  ansible.builtin.user:
    name: "{{ user.name }}"
    state: "{{ user.state }}"
    uid: "{{ user.uid | default(omit) }}"
    group: "{{ user.primary_group }}"
    groups: "{{ user.groups }}"
    # while we want the password locked, doing so prevents ssh login on certain platforms.
    # so we set it to * to prevent password login, but allow ssh key login.
    password_lock: false
    password: "*"
  loop: "{{ common_users }}"
  loop_control:
    loop_var: user

- name: Set common user ssh authorized_keys
  ansible.posix.authorized_key:
    user: "{{ user_key.name }}"
    key: "{{ user_key.sshpubkeys | map(attribute='key') | join('\n') }}"
    state: present
    exclusive: "{{ user_key.sshpubkeys_exclusive }}"
  loop: "{{ common_ssh_authorized_keys }}"
  loop_control:
    loop_var: user_key

- name: Ensure common doas user configuration
  ansible.builtin.lineinfile:
    path: /etc/doas.conf
    regexp: "^permit nopass {{ user.name }}"
    line: "permit nopass {{ user.name }}"
    mode: '0640'
    state: "{{ user.state }}"
    create: true
    backup: true
    validate: 'doas -C %s'
  loop: "{{ common_sudo_users }}"
  loop_control:
    loop_var: user
  when: ansible_become_method == 'community.general.doas'

- name: Ensure common doas group configuration
  ansible.builtin.lineinfile:
    path: /etc/doas.conf
    regexp: "^permit nopass :{{ group.name }}"
    line: "permit nopass :{{ group.name }}"
    mode: '0640'
    state: "{{ group.state }}"
    create: true
    backup: true
    validate: 'doas -C %s'
  loop: "{{ common_sudo_groups }}"
  loop_control:
    loop_var: group
  when: ansible_become_method == 'community.general.doas'

- name: Ensure common sudoer user configuration
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/00-ansible-common
    regexp: "^{{ user.name }}"
    line: "{{ user.name }} ALL=(ALL) NOPASSWD:ALL"
    mode: '0440'
    state: "{{ user.state }}"
    create: true
    backup: true
    validate: 'visudo -cf %s'
  loop: "{{ common_sudo_users }}"
  loop_control:
    loop_var: user
  when: ansible_become_method == 'ansible.builtin.sudo'

- name: Ensure common sudoer group configuration
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/00-ansible-common
    regexp: "^%{{ group.name }}"
    line: "%{{ group.name }} ALL=(ALL) NOPASSWD:ALL"
    mode: '0440'
    state: "{{ group.state }}"
    create: true
    backup: true
    validate: 'visudo -cf %s'
  loop: "{{ common_sudo_groups }}"
  loop_control:
    loop_var: group
  when: ansible_become_method == 'ansible.builtin.sudo'
