---
# tasks file for sshbastion
- name: Ensure sshbastion admin group exists
  ansible.builtin.group:
    name: "{{ sshbastion_admin_group.name }}"
    gid: "{{ sshbastion_admin_group.gid | default(omit) }}"
    state: "{{ sshbastion_admin_group.state | default('present') }}"
  tags:
    - ssh
    - group

- name: Ensure /etc/ssh/sshd_config.d/ exists
  ansible.builtin.file:
    path: /etc/ssh/sshd_config.d/
    state: directory
    owner: root
    group: 0
    mode: '0750'
  tags:
    - ssh
    - config

- name: Ensure sshd_config.d/ include directive exists
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    insertbefore: '^#Port 22'
    firstmatch: true
    line: 'Include /etc/ssh/sshd_config.d/*.conf'
    validate: '/usr/sbin/sshd -t -f %s'
  notify: "Common : restart sshd"
  tags:
  - ssh
  - config

- name: Insert sshd configuration directive to sshd_config.d/
  ansible.builtin.template:
    src: ../templates/sshd_bastion.conf.j2
    dest: "/etc/ssh/sshd_config.d/{{ sshbastion_dest_filename }}"
#    create: true
    owner: root
    group: 0
    mode: '0600'
    validate: /usr/sbin/sshd -t -f %s
    backup: yes
  notify:
    - "SSH bastion : restart sshd"
  tags:
    - ssh
    - config
