---
- name: Gather facts
  hosts: all
  gather_facts: true
  become: true
  become_method: community.general.doas # relies on prior install from packer CLI commands

- name: Bootstrap and provision packer image
  hosts: all
  become: true
  become_method: community.general.doas # relies on prior install from packer CLI commands
  tasks:
    - name: Include role(s)
      include_role:
        name: "{{ item }}"
      loop: "{{ common_roles }}"
