---
- name: Apply common configuration to prebaked image
  hosts: all
  gather_facts: yes
  become: yes
  become_method: doas
  tasks:
    - name: Include role(s)
      include_role:
        name: "{{ item }}"
      loop: "{{ packer_image_roles }}"
