---
- name: Apply configuration based on roles
  hosts: all
  connection: local
  gather_facts: true
  become: true
  become_method: community.general.doas
  tasks:
    - name: Include role based on tags
      ansible.builtin.include_role:
        name: "{{ item }}"
      loop: "{{ ['ansible-pull'] + hostvars['localhost']['roles'] }}"
      # loop: "{{ group_names }}"
      # when: item != "localhost" and item != "all"
