---
- name: Apply configuration based on roles
  hosts: all
  connection: local
  gather_facts: yes
  become: yes
  become_method: doas
  tasks:
    - name: Include role based on tags
      include_role:
        name: "{{ item }}"
      loop: "{{ ['common'] + hostvars['localhost']['roles'] }}"
      #loop: "{{ group_names }}"
      #when: item != "localhost" and item != "all"