---
- name: Apply configuration based on roles
  hosts: all
  gather_facts: true
  become: true
  become_method: community.general.doas
  tasks:
    - name: Include role based on tags
      ansible.builtin.include_role:
        name: "{{ item }}"
      loop: "{{ ['common'] + hostvars[inventory_hostname]['roles'] }}"