name: Lint, Validate, and Build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
    paths:
      - 'ansible/**'
      - 'packer/**'
      - '.github/workflows/unified-workflow.yml'
  workflow_dispatch:
  schedule:
    - cron: '36 12 * * 0' # Every Sunday at 12:36 UTC

jobs:
  setup-and-validate:
    name: Setup and Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Ansible and dependencies
        working-directory: ansible
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Ansible collections/roles
        working-directory: ansible
        run: |
          ansible-galaxy install -r requirements.yml

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION || secrets.AWS_DEFAULT_REGION || 'us-east-1' }}

      - name: Lint all Ansible code
        working-directory: ansible
        run: ansible-lint .

      - name: Set up Packer
        uses: hashicorp/setup-packer@v3
        with:
          version: latest

      - name: Validate Packer template
        env:
          PKR_VAR_rename_default_user_to: ${{ vars.PKR_VAR_RENAME_DEFAULT_USER_TO }}
        run: |
          cd packer
          packer init alpine-custom.pkr.hcl
          packer validate alpine-custom.pkr.hcl

  packer-build-dev:
    name: Build Alpine AMI (Dev)
    runs-on: ubuntu-latest
    needs: setup-and-validate
    if: github.event_name == 'workflow_dispatch' && github.ref != 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Packer
        uses: hashicorp/setup-packer@v3
        with:
          version: latest

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Ansible and dependencies
        working-directory: ansible
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Ansible collections/roles
        working-directory: ansible
        run: |
          ansible-galaxy install -r requirements.yml

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION || 'us-east-1' }}

      - name: Build Alpine AMI with Packer (Dev)
        env:
          PKR_VAR_rename_default_user_to: ${{ vars.PKR_VAR_RENAME_DEFAULT_USER_TO }}
        run: |
          cd packer
          packer init alpine-custom.pkr.hcl
          packer build -var-file=dev.auto.pkrvars.hcl alpine-custom.pkr.hcl

  packer-build-prod:
    name: Build Alpine AMI (Prod)
    runs-on: ubuntu-latest
    needs: setup-and-validate
    if: (github.event_name == 'workflow_dispatch' || github.event_name == 'schedule') && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Packer
        uses: hashicorp/setup-packer@v3
        with:
          version: latest

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Ansible and dependencies
        working-directory: ansible
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Ansible collections/roles
        working-directory: ansible
        run: |
          ansible-galaxy install -r requirements.yml

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION || 'us-east-1' }}

      - name: Build Alpine AMI with Packer (Prod)
        env:
          PKR_VAR_rename_default_user_to: ${{ vars.PKR_VAR_RENAME_DEFAULT_USER_TO }}
        run: |
          cd packer
          packer init alpine-custom.pkr.hcl
          packer build -var-file=prod.pkrvars.hcl alpine-custom.pkr.hcl